[
{'personaje':'Batman',
'nombre': 'Bruce Wayne',
'nacimiento':'27 de Junio',
'origen':'Gotham City', 
'reside':'Gotham City',
'afiliaciones': 'Liga de la Justicia, Batfamily',
'habilidades':'Batman es un maestro en artes marciales, posee una fuerza y resistencia excepcionales, y es un genio táctico y estratégico. Además, es un experto detective y cuenta con una amplia gama de gadgets y tecnología avanzada que utiliza en su lucha contra el crimen.',
'historia': 'Bruce Wayne presenció el asesinato de sus padres a una temprana edad, lo que lo impulsó a dedicar su vida a combatir la delincuencia y la corrupción en Gotham City. Entrenó su cuerpo y mente en todo tipo de disciplinas, y adoptó la identidad de Batman, un vigilante oscuro y temido por los criminales. Utilizando su riqueza y recursos, Batman se convierte en el protector de Gotham y busca hacer justicia de manera implacable.',
'amor':'Catwoman y Talia al Ghul',
'creador':'Bill Finger y Bob Kane',
'aliados':'Robin, Batgirl, Nightwing',
'enemigos':'Joker, Dos Caras, Enigma'
},
{'personaje': 'Superman',
'nombre': 'Clark Kent',
'nacimiento': '3 de junio',
'origen': 'Smallville',
'reside': 'Metropolis',
'afiliaciones': 'Liga de la Justicia',
'habilidades': 'Superman posee una fuerza sobrehumana, velocidad extraordinaria, la capacidad de volar, visión de rayos X y calor, aliento helado y una invulnerabilidad casi total. También es un experto en combate cuerpo a cuerpo y estrategia.',
'historia': 'Clark Kent, un alienígena del planeta Krypton, fue enviado a la Tierra cuando era un bebé. Fue criado en Smallville por Jonathan y Martha Kent, quienes le inculcaron valores de bondad y justicia. Con el tiempo, descubre sus poderes y adopta la identidad de Superman, el defensor de la verdad, la justicia y el estilo de vida estadounidense en Metropolis.',
'amor': 'Lois Lane',
'creador': 'Jerry Siegel y Joe Shuster',
'aliados': 'Wonder Woman, Supergirl, Lois Lane',
'enemigos': 'Lex Luthor, General Zod, Brainiac'
},
{'personaje': 'Green Lantern',
'nombre': 'Hal Jordan',
'nacimiento': '20 de enero',
'origen': 'Coast City',
'reside': 'Sector Espacial 2814',
'afiliaciones': 'Liga de la Justicia, Green Lantern Corps',
'habilidades': 'Green Lantern posee un anillo de poder que le otorga la capacidad de crear construcciones sólidas con su mente, volar, generar escudos protectores y manifestar la energía de la voluntad. Además, es un piloto excepcional y tiene una gran fuerza de voluntad.',
'historia': 'Hal Jordan era un piloto de pruebas talentoso que fue elegido por un anillo de poder extraterrestre para convertirse en Green Lantern, miembro del Green Lantern Corps. Con el anillo, protege el universo de amenazas intergalácticas y defiende la justicia y el orden en su sector espacial. Hal Jordan se enfrenta a desafíos personales y lucha contra enemigos poderosos mientras equilibra su vida como Green Lantern y su vida terrenal.',
'amor': 'Carol Ferris',
'creador': 'John Broome y Gil Kane',
'aliados': 'Superman, Flash, John Stewart',
'enemigos': 'Sinestro, Atrocitus, Star Sapphire'
},
{'personaje': 'Wonder Woman',
'nombre': 'Diana Prince',
'nacimiento': '20 de octubre',
'origen': 'Themyscira',
'reside': 'Themyscira / Mansión de la Justicia',
'afiliaciones': 'Liga de la Justicia, Amazonas',
'habilidades': 'Wonder Woman es una guerrera amazona con una fuerza y resistencia sobrehumanas. También posee habilidades de vuelo, invulnerabilidad, capacidad de sanación acelerada y habilidades de combate excepcionales. Además, porta armas como el Lazo de la Verdad y los Brazaletes de la Sumisión.',
'historia': 'Diana Prince es la princesa de Themyscira, una isla habitada exclusivamente por amazonas. Criada para ser una guerrera, Diana se convierte en Wonder Woman y viaja al mundo de los hombres para luchar por la justicia y la paz. Como embajadora de Themyscira, Wonder Woman utiliza su fuerza y sabiduría para proteger a los inocentes y enfrentar amenazas tanto humanas como sobrenaturales.',
'amor': 'Steve Trevor',
'creador': 'William Moulton Marston',
'aliados': 'Liga de la Justicia, Superman, Batman',
'enemigos': 'Ares, Cheetah, Circe'
},
{'personaje': 'Flash',
'nombre': 'Barry Allen',
'nacimiento': '20 de marzo',
'origen': 'Central City',
'reside': 'Central City',
'afiliaciones': 'Liga de la Justicia',
'habilidades': 'Flash posee una velocidad sobrehumana, lo que le permite correr a velocidades increíbles, atravesar objetos sólidos, viajar en el tiempo y generar ráfagas de energía. También tiene reflejos y agilidad mejorados.',
'historia': 'Barry Allen era un científico forense que, tras ser alcanzado por un rayo durante un accidente con productos químicos, adquirió la capacidad de correr a velocidades supersónicas. Adopta el nombre de Flash y se convierte en el defensor de Central City, utilizando sus poderes para proteger a los inocentes y combatir el crimen.',
'amor': 'Iris West',
'creador': 'Robert Kanigher, John Broome y Carmine Infantino',
'aliados': 'Liga de la Justicia, Kid Flash, Jesse Quick',
'enemigos': 'Reverse-Flash, Captain Cold, Zoom'
},
{
'personaje': 'Robin',
'nombre': 'Tim Drake',
'nacimiento': '27 de abril',
'origen': 'Gotham City',
'reside': 'Gotham City',
'afiliaciones': 'Liga de la Justicia, Batfamily',
'habilidades': 'Robin es un experto en artes marciales y acrobacias, con una agilidad y destreza excepcionales. Además, es un talentoso hacker y estratega. Utiliza una variedad de gadgets y armas no letales en su lucha contra el crimen.',
'historia': 'Tim Drake es un joven que dedica su vida a combatir el crimen en Gotham City como el compañero y aprendiz de Batman. Después de presenciar un acto heroico de Batman, Tim descubre la identidad secreta de Bruce Wayne y convence a Batman de que lo acepte como el nuevo Robin. Tim se convierte en un valioso miembro de la Batfamily, ayudando a proteger Gotham y luchar contra los villanos.',
'amor': 'Stephanie Brown',
'creador': 'Marv Wolfman y Pat Broderick',
'aliados': 'Batman, Batgirl, Nightwing',
'enemigos': 'Joker, Dos Caras, Enigma'
},
{
'personaje': 'Alfred Pennyworth',
'nombre': 'Alfred Pennyworth',
'nacimiento': '2 de mayo',
'origen': 'Londres',
'reside': 'Mansión Wayne',
'afiliaciones': 'Batfamily',
'habilidades': 'Alfred es un hábil mayordomo con conocimientos en medicina, cocina, mantenimiento y manejo de la logística de la Batcave. Además, es un experto en tecnología y apoya a Batman como consejero y confidente.',
'historia': 'Alfred Pennyworth es un leal mayordomo que ha servido a la familia Wayne durante generaciones. Después del asesinato de los padres de Bruce Wayne, Alfred asume el papel de tutor y mentor de Bruce. Apoya a Bruce en su lucha contra el crimen y despliega sus habilidades para ayudar a mantener el secreto de Batman.',
'amor': 'N/A (No tiene un interés amoroso principal en los cómics)',
'creador': 'Bob Kane y Jerry Robinson',
'aliados': 'Batman, Batgirl, Robin',
'enemigos': 'N/A (No tiene enemigos principales)'
},
{
'personaje': 'Catwoman',
'nombre': 'Selina Kyle',
'nacimiento': '8 de abril',
'origen': 'Gotham City',
'reside': 'Gotham City',
'afiliaciones': 'Batfamily',
'habilidades': 'Catwoman es una experta en artes marciales, sigilo y acrobacias. Posee agilidad sobrehumana, sentidos agudizados y habilidades de robo. Además, tiene una conexión especial con los gatos y utiliza un látigo como su arma distintiva.',
'historia': 'Selina Kyle es una hábil ladrona que opera en las calles de Gotham City. Aunque inicialmente se cruza en el camino de Batman como una villana, con el tiempo se convierte en una antiheroína y aliada ocasional de Batman. Catwoman lucha por sus propios intereses y tiene una compleja relación con Batman, a veces como aliada y otras veces como enemiga.',
'amor': 'Batman/Bruce Wayne',
'creador': 'Bill Finger y Bob Kane',
'aliados': 'Batman, Batfamily',
'enemigos': 'Joker, Dos Caras, Pingüino'
},
{
'personaje': 'Poison Ivy',
'nombre': 'Pamela Isley',
'nacimiento': '29 de mayo',
'origen': 'Seattle',
'reside': 'Gotham City',
'afiliaciones': 'Villanos de Batman',
'habilidades': 'Poison Ivy tiene la capacidad de controlar las plantas y liberar toxinas y feromonas letales. Es inmune a muchas sustancias venenosas y tiene una conexión única con la flora. Además, posee habilidades de seducción y manipulación.',
'historia': 'Pamela Isley era una brillante botánica que, después de un experimento fallido, adquirió poderes relacionados con las plantas. Bajo el alias de Poison Ivy, utiliza su control sobre la vegetación para proteger la naturaleza y vengarse de aquellos que la dañan. Su conflicto con Batman radica en sus métodos extremos y su defensa despiadada de la ecología.',
'amor': 'N/A (Ha tenido interés romántico en Batman en algunas versiones de los cómics)',
'creador': 'Robert Kanigher y Sheldon Moldoff',
'aliados': 'Harley Quinn, algunas veces Catwoman',
'enemigos': 'Batman, Robin, Batgirl'
},
{
'personaje': 'Penguin',
'nombre': 'Oswald Cobblepot',
'nacimiento': '12 de diciembre',
'origen': 'Gotham City',
'reside': 'Gotham City',
'afiliaciones': 'Villanos de Batman',
'habilidades': 'Penguin es un maestro estratega y manipulador. Tiene una mente astuta y es hábil en el manejo de la manipulación política y empresarial. Además, es experto en el uso de armas de fuego y tiene una colección de paraguas especiales que utiliza en sus planes y combates.',
'historia': 'Oswald Cobblepot, apodado Penguin por su apariencia física y su amor por las aves, es un infame gángster y supervillano en Gotham City. Con su imagen de empresario respetable, se involucra en actividades criminales y busca controlar el bajo mundo de la ciudad. Penguin es conocido por su intelecto y su capacidad para manipular a otros en beneficio propio.',
'amor': 'N/A (No tiene un interés amoroso principal en los cómics)',
'creador': 'Bob Kane y Bill Finger',
'aliados': 'Villanos de Batman (según sus propios intereses)',
'enemigos': 'Batman, Robin, Comisionado James Gordon'
},
{
'personaje': 'Joker',
'nombre': 'Desconocido',
'nacimiento': 'Desconocido',
'origen': 'Desconocido',
'reside': 'Gotham City',
'afiliaciones': 'Villanos de Batman',
'habilidades': 'Joker es impredecible y altamente peligroso. Es un maestro del caos y la manipulación psicológica. Tiene una mente brillante pero perturbada, lo que le permite planificar elaborados crímenes y trampas mortales. Además, es hábil en el uso de armas improvisadas y toxinas letales.',
'historia': 'El origen del Joker es incierto y ha sido reinventado en varias ocasiones. Es conocido como el archienemigo de Batman y es famoso por su risa maníaca y su obsesión por sembrar el caos en Gotham City. El Joker representa la anarquía y desafía constantemente las normas sociales y la cordura.',
'amor': 'Harley Quinn',
'creador': 'Jerry Robinson, Bill Finger y Bob Kane',
'aliados': 'Harley Quinn, algunos villanos de Batman (según sus propios intereses)',
'enemigos': 'Batman, Robin, Batgirl'
},
{
'personaje': 'Nekrón',
'nombre': 'Desconocido',
'nacimiento': 'Desconocido',
'origen': 'Reino Oscuro',
'reside': 'Reino Oscuro',
'afiliaciones': 'Villanos de Green Lantern',
'habilidades': 'Nekrón es una entidad cósmica asociada con la muerte y la oscuridad. Tiene el poder de manipular la energía negra y controlar a los muertos. Puede invocar a los espíritus y usar su poder para corromper y desestabilizar a otros seres. Además, es prácticamente inmortal y posee un conocimiento vasto sobre la vida y la muerte.',
'historia': 'Nekrón es una entidad primordial que gobierna sobre el Reino Oscuro, un plano de existencia asociado con la muerte. Su objetivo es expandir su dominio sobre todas las formas de vida y llevar la oscuridad a todo el universo. Se ha enfrentado en repetidas ocasiones a los Green Lantern Corps y a otros héroes cósmicos en su búsqueda de la aniquilación.',
'amor': 'N/A (No tiene un interés amoroso principal en los cómics)',
'creador': 'Peter Tomasi y Doug Mahnke',
'aliados': 'Varios villanos cósmicos (según sus propios intereses)',
'enemigos': 'Green Lantern Corps, héroes cósmicos'
},
{
'personaje': 'Darkseid',
'nombre': 'Uxas',
'nacimiento': 'Desconocido',
'origen': 'Apokolips',
'reside': 'Apokolips',
'afiliaciones': 'Villanos de DC Comics',
'habilidades': 'Darkseid es uno de los seres más poderosos del universo DC. Posee fuerza y resistencia sobrehumanas, así como la capacidad de volar. Su visión omega le permite disparar rayos de energía destructiva. Además, es un estratega maestro y tiene acceso a la tecnología avanzada de Apokolips.',
'historia': 'Darkseid es el gobernante tiránico de Apokolips, un mundo infernal obsesionado con la conquista universal y la erradicación del libre albedrío. Busca el Anti-Vida Equation, un poderoso artefacto que le daría el control total sobre todos los seres vivos. Darkseid es un enemigo formidable de la Liga de la Justicia y ha librado numerosas batallas con los héroes de la Tierra.',
'amor': 'Desaad (en algunas versiones de los cómics)',
'creador': 'Jack Kirby',
'aliados': 'New Gods, Parademons',
'enemigos': 'Superman, Batman, Wonder Woman, Liga de la Justicia'
},
{
'personaje': 'Salvatore Maroni',
'nombre': 'Salvatore Vincent Maroni',
'nacimiento': 'Desconocido',
'origen': 'Gotham City',
'reside': 'Gotham City',
'afiliaciones': 'Familia Maroni, Gángsters de Gotham',
'habilidades': 'Salvatore Maroni es un gángster astuto y despiadado. Tiene habilidades en el mundo del crimen organizado, incluyendo el tráfico de drogas, extorsión y asesinato. Además, es conocido por su capacidad para mantener el control y la lealtad de su familia y sus asociados.',
'historia': 'Salvatore Maroni es un destacado miembro de la Familia Maroni, una poderosa organización criminal en Gotham City. A lo largo de su carrera criminal, ha estado involucrado en diversas actividades delictivas y ha sido un enemigo recurrente de Batman y la ley. Maroni es conocido por su rivalidad con la Familia Falcone y su participación en el origen del villano Dos Caras.',
'amor': 'Desconocido',
'creador': 'Bob Kane y Bill Finger',
'aliados': 'Familia Maroni, otros gángsters de Gotham',
'enemigos': 'Batman, Harvey Dent (Dos Caras), Familia Falcone'
}

]